//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelationDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartID { get; set; }
        public Nullable<int> TrainingRoutineID { get; set; }
        public Nullable<int> DietID { get; set; }
        public Nullable<int> SupplementID { get; set; }
        public Nullable<int> TrainingEquipmentID { get; set; }
        public string PurchaserID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> PersonalTrainingSessionPersonalTrainingID { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual Diet Diet { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual PersonalTraining PersonalTraining { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplement Supplement { get; set; }
        public virtual TrainingEquipment TrainingEquipment { get; set; }
        public virtual TrainingRoutine TrainingRoutine { get; set; }
    }
}
