//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelationDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int OrderDetailID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> TrainingRoutineID { get; set; }
        public Nullable<int> DietID { get; set; }
        public Nullable<int> SupplementID { get; set; }
        public Nullable<int> TrainingEquipmentID { get; set; }
        public string PurchaserID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.Guid> OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime OrderUpdated { get; set; }
        public int CurrentOrderItemNumber { get; set; }
        public int PTSessionType { get; set; }
        public int LengthOfRoutine { get; set; }
        public int ExperienceLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Diet Diet { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplement Supplement { get; set; }
        public virtual TrainingEquipment TrainingEquipment { get; set; }
        public virtual TrainingRoutine TrainingRoutine { get; set; }
    }
}
