//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelationDiagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductContextDBEntities : DbContext
    {
        public ProductContextDBEntities()
            : base("name=ProductContextDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Diet> Diets { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<PersonalTraining> PersonalTrainings { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplement> Supplements { get; set; }
        public virtual DbSet<TFRoleClaim> TFRoleClaims { get; set; }
        public virtual DbSet<TFRole> TFRoles { get; set; }
        public virtual DbSet<TFUserClaim> TFUserClaims { get; set; }
        public virtual DbSet<TFUserLogin> TFUserLogins { get; set; }
        public virtual DbSet<TFUser> TFUsers { get; set; }
        public virtual DbSet<TFUserToken> TFUserTokens { get; set; }
        public virtual DbSet<TrainingEquipment> TrainingEquipments { get; set; }
        public virtual DbSet<TrainingRoutine> TrainingRoutines { get; set; }
    }
}
