//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> DietID { get; set; }
        public Nullable<int> SupplementID { get; set; }
        public Nullable<int> TrainingEquipmentID { get; set; }
        public Nullable<int> TrainingRoutineID { get; set; }
        public decimal Price { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.Guid OrderNumber { get; set; }
        public System.DateTime OrderUpdated { get; set; }
        public string PurchaserID { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Diet Diet { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplement Supplement { get; set; }
        public virtual TrainingEquipment TrainingEquipment { get; set; }
        public virtual TrainingRoutine TrainingRoutine { get; set; }
    }
}
