//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductContext_59a25d91_3b23_442e_9df3_9a1daed97a84Entities : DbContext
    {
        public ProductContext_59a25d91_3b23_442e_9df3_9a1daed97a84Entities()
            : base("name=ProductContext_59a25d91_3b23_442e_9df3_9a1daed97a84Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Diet> Diets { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PersonalTraining> PersonalTrainings { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplement> Supplements { get; set; }
        public virtual DbSet<TrainingEquipment> TrainingEquipments { get; set; }
        public virtual DbSet<TrainingRoutine> TrainingRoutines { get; set; }
    }
}
